os: linux
node_js: '7'
sudo: required
env: DISPLAY=':99.0'
dist: trusty
language: ruby

rvm:
  - 2.5.0

services:
  - elasticsearch

addons:
  postgresql: "9.4"
  chrome: stable
  apt:
    sources:
      - google-chrome

before_script:
  - sleep 10
  - sh -e /etc/init.d/xvfb start
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - node --version
  - npm --version
  - yarn install

script: 
  - bundle exec rake db:schema:load
  - bundle exec rspec
